import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // Geist kaldırıldı
import { Montserrat } from "next/font/google"; // Montserrat eklendi
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from 'react-hot-toast';

// Geist kaldırıldı
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

// Montserrat yapılandırması
const montserrat = Montserrat({
  subsets: ["latin"], // Latin alfabesi
  variable: "--font-montserrat", // CSS değişkeni adı
  weight: ['400', '500', '600', '700'], // İhtiyaç duyulabilecek ağırlıklar
});

export const metadata: Metadata = {
  title: "Kişisel Yönetim Paneli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
        className={`${montserrat.variable} font-sans antialiased flex`} // Montserrat değişkeni ve varsayılan sans fontu eklendi
      >
        <Navbar />
        <main className="flex-grow p-8 overflow-y-auto">
          {children}
        </main>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
